version: '2'
services:
  odoo-db:
    container_name: odoo-db
    image: postgres:${PG_VERSION:-15}
    user: root
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-odoo}
      - POSTGRES_USER=${DB_USER:-odoo}
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo-app:
    container_name: odoo-app
    image: odoo:${ODOO_VERSION:-16}
    user: root
    depends_on:
      - odoo-db
    ports:
      - "${APP_PORT:-10016}:8069"
      # - "20014:8072" # live chat
    # expose: # in case you want to use reverse proxy server
    #   - ""${APP_PORT:-10016}"
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=odoo-db
      - USER=${DB_USER:-odoo}
      - PASSWORD=${DB_PASSWORD:-odoo}
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service