name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          USERNAME: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          script: |
            if [ ! -d ~/$REPO ]
            then
            sudo git clone https://github.com/$USERNAME/$REPO.git
            else
            sudo git -C ~/$REPO pull 
            fi
            sudo docker-compose -f ~/$REPO/docker-compose.prod.yml up --build --force-recreate --no-deps -d
            echo $USERNAME - $REPO - ${{ github.repositoryUrl }}
            