name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          REPO: ${{ github.repository }} # e.g. "appleboy/ssh-action"
          DIRECTORY: ${{ github.event.repository.name }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          # TOKEN: ${{ github.token }}
        with: 
          envs: REPO, DIRECTORY, DB_NAME, DB_USERNAME, DB_PASSWORD
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          script: |
            if [ ! -d ~/$DIRECTORY ]
            then
            sudo git clone https://github.com/$REPO.git
            else
            sudo git -C ~/$DIRECTORY pull 
            fi
            sudo rm ~/$DIRECTORY/.env
            touch .env
            echo DB_NAME="$DB_NAME" > .env
            echo DB_USERNAME="$DB_USERNAME" > .env
            echo DB_PASSWORD="$DB_PASSWORD" > .env
            sudo docker-compose -f ~/$DIRECTORY/docker-compose.prod.yml up --build --force-recreate --no-deps -d
            echo $DIRECTORY - $REPO

            