name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          script: |
            if [ ! -d ~/${{ github.repository }} ]
            then
            sudo git clone https://github.com/${{ github.repository_owner }}/${{ github.repository }}.git
            else
            sudo git -C ~/${{ github.repository }} pull 
            fi
            sudo docker-compose -f ~/${{ github.repository }}/docker-compose.prod.yml up --build --force-recreate --no-deps -d
            echo ${{ github.repository_owner }} - ${{ github.repository }} - ${{ github.repositoryUrl }}
            