name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}

      - name: git pull
        run: |
            if [ ! -d ~/${{ github.event.repository.name }} ]
            then
            sudo git clone https://github.com/${{ github.repository }}.git
            else
            sudo git -C ~/${{ github.event.repository.name }} pull 
            fi
      
      - name: make .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_: ${{ secrets.ODOO_DB }}
          directory: ~/my-odoo/


      - name: docker-compose up
        run: |
            sudo docker-compose -f ~/${{ github.event.repository.name }}/docker-compose.prod.yml up --build --force-recreate --no-deps -d





            