name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          script: |
            if [ ! -d ~/<repo> ]
            then
            git clone https://github.com/<name>/<repo>.git
            else
            git -C ~/<repo> pull 
            fi
            sudo docker-compose -f ~/<repo>/docker-compose.prod.yml up --build --force-recreate --no-deps -d
            echo "done"
            